# prepare  exports
- name: create storage domain directory
  file: state=directory path={{ item.path }} mode=0755 owner=36 group=36
  with_items: "{{ rhev_storage_domains }}"
- name: create /etc/exports entry
  lineinfile: dest=/etc/exports line="{{ item.path }} {{ infrastructure_network_admin.host_prefix }}(rw,sync,no_subtree_check,all_squash,anonuid=36,anongid=36)"
  register: etc_exports
  with_items: "{{ rhev_storage_domains }}"
- name: export file systems
  command: exportfs -a
  when: etc_exports|changed
