- block:
    - name: ensure that root has an ssh key set
      user: name=root generate_ssh_key=yes ssh_key_bits=2048 ssh_key_file=.ssh/id_rsa
    - name: get installer root pubkey
      command: cat .ssh/id_rsa.pub
      register: root_pub_key
      failed_when: root_pub_key.stdout == ''
      changed_when: false
      delegate_to: ose3-master
    - name: set root ssh key as authorized key
      authorized_key: user=root key={{ root_pub_key.stdout }}
  when: mode=="create"
