# prepare host
- name: ensure that root has an ssh key set
  user: name=root generate_ssh_key=yes ssh_key_bits=2048 ssh_key_file=.ssh/id_rsa
- name: get root pubkey
  command: cat .ssh/id_rsa.pub
  register: root_pub_key
  failed_when: root_pub_key.stdout == ''
  changed_when: false
- name: set root ssh key as authorized key
  authorized_key: user=root key={{ root_pub_key.stdout }}
- name: copy ssh pubkey to layer1
  authorized_key: user=root key={{ ssh_pub_key_hailstorm }}
- name: ensure KVM nested virtualization is enabled
  #lineinfile: dest=/etc/modprobe.d/kvm-intel.conf line="options kvm-intel nested=y" create=yes state=present
  copy: src=../templates/kvm-intel.conf dest=/etc/modprobe.d/kvm-intel.conf mode=0644
  notify:
    - restart machine
    - waiting for server to come back

# TODO: ensure proper subscription & configure channels
# see layer2_rhel

- name: system-upgrade
  yum: name=* state=latest
- name: ensure prerequisite packages are present
  yum: name=libvirt,libvirt-client,qemu-kvm,qemu-img,libvirt-python,virt-install,nfs-utils state=latest
  notify: #reboot machine if necessary https://bugzilla.redhat.com/show_bug.cgi?id=950436
    - restart machine
    - waiting for server to come back
- name: enable and start libvirtd
  service: name=libvirtd enabled=yes state=started
