- name: updating firewall rules
  firewalld: port={{item.port}}/{{item.protocol}} permanent={{item.permanent}} state={{item.state }} zone={{item.zone}}
  with_items:  "{% if firewalld_rules is defined %}{{ firewalld_rules }}{% endif %}"
  register: firewalld_conf_update
  when: not (firewalld_rules is undefined or firewalld_rules is none or firewalld_rules | trim == '')

- name: restart firewalld
  service: name=firewalld state=restarted enabled=yes
  when: not (firewalld_rules is undefined or firewalld_rules is none or firewalld_rules | trim == '') and firewalld_conf_update|changed
