# TODO: replace with ../../common/handlers/reboot.yml
- name: restart machine
  command: shutdown -r now "Ansible updates triggered"
  async: 0
  poll: 0
  ignore_errors: true
- name: waiting for server to come back
  local_action: wait_for host={{ ansible_host }} port=22 delay=30 timeout=600
  become: false
