mem: 2048
vcpu: 2
disk:
  path: "{{ inventory_hostname_short }}.qcow2"
  size: 30
  format: qcow2
  partition_table:
    lvmpv: 29500
    swap: 2048
    home: 2048
    root: 10000

pool_regex: "{{ rhel_subscription_pool_regex }}"
