- stat: path=/etc/ovirt-engine/aaa/IPA.jks
  register: ldap_keystore

- block:
# main process


# resolv.conf needs to point to IPA


# copy the ca.crt from IPA (using delegate)
    - name: copy certificate of IPA
      command: cat /etc/ipa/ca.crt
      delegate_to: ipa
      register: certificate

    - name: create the cert on the RHEV server
      copy: content="{{ certificate.stdout }}" dest=/tmp/ca.crt

    # run the keytool line to generate the store
    - name: generate keystore file from cert
      command: keytool -importcert -noprompt -trustcacerts -alias ca -file /tmp/ca.crt -keystore /etc/ovirt-engine/aaa/IPA.jks -storepass changeit  creates=/etc/ovirt-engine/aaa/IPA.jks

    # copy the other 3 files over
    #- name: copy IPA.properties
    #  copy: src=files/IPA.properties dest=/etc/ovirt-engine/aaa/IPA.properties owner=ovirt group=ovirt mode=600
    - name: create IPA.properties
      template: src=IPA.properties.j2 dest=/etc/ovirt-engine/aaa/IPA.properties owner=ovirt group=ovirt mode=0600

    # - name: copy IPA-authz.properties
    #   copy: src=files/IPA-authz.properties dest=/etc/ovirt-engine/extensions.d/IPA-authz.properties
    - name: create IPA-authz.properties
      template: src=IPA-authz.properties.j2 dest=/etc/ovirt-engine/extensions.d/IPA-authz.properties

    # - name: copy IPA-authn.properties
    #   copy: src=files/IPA-authn.properties dest=/etc/ovirt-engine/extensions.d/IPA-authn.properties
    - name: create IPA-authn.properties
      template: src=IPA-authn.properties.j2 dest=/etc/ovirt-engine/extensions.d/IPA-authn.properties

    # restart ovirt-engine
    - name: restarting rhev services
      service: name=ovirt-engine state=restarted

    # add an LDAP group to the RHEV superuser role

    - name: create .rhevmshellrc
      template: src=rhevmshellrc.j2 dest=/root/.rhevmshellrc mode=0600

    - name: create ipausers group
      shell: rhevm-shell -E 'add group --name ipausers --domain-name IPA-authz' | grep -e "^id" | cut -c18-
      register: ipausers_group_id

    - name: get SuperUser role id
      shell: rhevm-shell -E 'show role SuperUser' | grep -e "^id" | cut -c18-
      register: superuser_role_id

    - name: create permission for ipausers
      shell: rhevm-shell -E 'add permission --role-id {{ superuser_role_id.stdout }} --group-id {{ ipausers_group_id.stdout }}'


  when: ldap_keystore.stat.exists == False
