- name: enable repositories for Satellite 6.1 (to be able to self register)
  command: 'hammer repository-set enable --organization "Default Organization" --basearch "x86_64" {{ item }}'
  with_items:
    - '--product "Red Hat Satellite" --name "Red Hat Satellite 6.1 (for RHEL 7 Server) (RPMs)"'
    - '--product "Red Hat Software Collections for RHEL Server" --name "Red Hat Software Collections RPMs for Red Hat Enterprise Linux 7 Server" --releasever "7Server"'
  ignore_errors: yes

- name: start sync tasks for Satellite 6.1 repos
  command: 'hammer product synchronize --async --organization "Default Organization" {{ item }}'
  with_items:
    - '--name "Red Hat Satellite"'
    - '--name "Red Hat Software Collections for RHEL Server"'
