# "ignore_errors: yes" because hammer throws an error if we try to enable a repo, that is already enabled
- name: enable RHEL repos
  command: 'hammer repository-set enable --organization "Default Organization" --product "Red Hat Enterprise Linux Server" --basearch="x86_64" {{ item }}'
  with_items:
    - '--name "Red Hat Enterprise Linux 7 Server (RPMs)" --releasever="7Server"'
    - '--name "Red Hat Enterprise Linux 7 Server - Extras (RPMs)"'
    - '--name "Red Hat Enterprise Linux 7 Server - Optional (RPMs)"'
    - '--name "Red Hat Enterprise Linux 7 Server (Kickstart)" --releasever="7.2"'
    - '--name "Red Hat Satellite Tools 6.1 (for RHEL 7 Server) (RPMs)"'
    - '--name "Red Hat Enterprise Linux 6 Server (RPMs)" --releasever="6Server"'
    - '--name "Red Hat Enterprise Linux 6 Server - Supplementary (RPMs)" --releasever="6Server"'
    - '--name "Red Hat Enterprise Linux 6 Server (Kickstart)" --releasever="6.7"'
    - '--name "Red Hat Satellite Tools 6.1 (for RHEL 6 Server) (RPMs)"'
  ignore_errors: yes

- name: start sync tasks for RHEL repos
  command: 'hammer product synchronize --async --organization "Default Organization" --name "Red Hat Enterprise Linux Server"'
