- name: enable RHEV repos
  command: 'hammer repository-set enable --organization "Default Organization" --basearch "x86_64" --product "Red Hat Enterprise Virtualization" {{ item }}'
  with_items:
    - '--name "Red Hat Enterprise Virtualization Management Agents for RHEL 7 (RPMs)" --releasever="7Server"'
    - '--name "Red Hat Enterprise Virtualization Manager 3.6 (RPMs)"'
  ignore_errors: yes

- name: enable JBoss EAP 6 repo
  command: 'hammer repository-set enable --organization "Default Organization" --product "JBoss Enterprise Application Platform" --name "JBoss Enterprise Application Platform 6 (RHEL 6 Server) (RPMs)" --basearch "x86_64" --releasever "6Server"'
  ignore_errors: yes

- name: start sync tasks for RHEV repos
  command: 'hammer product synchronize --async --organization "Default Organization" --name "Red Hat Enterprise Virtualization"'

- name: start sync task for JBoss EAP 6 repo
  command: 'hammer product synchronize --async --organization "Default Organization" --name "JBoss Enterprise Application Platform"'
