- name: read ironic uuids
  shell: >
    . ~/stackrc && echo {{ item }} &&
    openstack baremetal show -f value -c uuid -c instance_uuid
    $(ironic port-show --address {{ hostvars[item].vm_nics[0].mac }} | awk '/node_uuid/{ print $4 }')
  become: yes
  become_user: "{{ rhosp_stack_user }}"
  with_items: "{{ groups['rhosp-undercloud'] }}"
  register: ironic_uuids
  changed_when: false
- debug: var=ironic_uuids
