---

- hosts: ose3
  gather_facts: false
  remote_user: root
  roles:
    - role: layer2_vms
      tags: [ 'layer2','ose3', 'rhel' ]
      mode: start
    - role: layer2_rhel
      tags: [ 'layer2','ose3', 'rhel' ]
      mode: destroy
    - role: layer2_vms
      tags: [ 'layer2','ose3', 'vms' ]
      mode: destroy


- hosts: rhev
  gather_facts: false
  remote_user: root
  roles:
    - role: layer2_vms
      tags: [ 'layer2','rhev', 'rhel' ]
      mode: start
    - role: layer2_rhel
      tags: [ 'layer2','rhev', 'rhel' ]
      mode: destroy
    - role: layer2_vms
      tags: [ 'layer2','rhev', 'vms' ]
      mode: destroy

- hosts: rhevm
  gather_facts: false
  remote_user: root
  roles:
    - role: layer3_cloudforms_rhev
      tags: [ 'layer3', 'cf' ]
      mode: destroy


- hosts: rhosp-director
  gather_facts: false
  remote_user: root
  roles:
    - role: layer2_vms
      tags: [ 'layer2','rhosp', 'rhel' ]
      mode: start
    - role: layer2_rhosp_overcloud
      tags: [ 'layer2', 'rhosp', 'overcloud' ]
      mode: destroy
    - role: layer2_rhosp_director
      tags: [ 'layer2', 'rhosp', 'undercloud' ]
      mode: destroy
    - role: layer2_rhel
      tags: [ 'layer2','rhosp', 'rhel'  ]
      mode: destroy

- hosts: rhosp-all
  gather_facts: false
  remote_user: root
  roles:
    - role: layer2_vms
      tags: [ 'layer2','rhosp', 'vms' ]
      mode: destroy

- hosts: ipa
  gather_facts: false
  remote_user: root
  roles:
    - role: layer2_vms
      tags: [ 'layer2','ipa', 'rhel' ]
      mode: start
    - role: layer2_ipa
      tags: [ 'layer2', 'ipa' ]
      mode: destroy
    - role: layer2_rhel
      tags: [ 'layer2','ipa', 'rhel' ]
      mode: destroy
    - role: layer2_vms
      tags: [ 'layer2','ipa', 'vms' ]
      mode: destroy


- hosts: infrastructure
  gather_facts: false
  remote_user: root
  roles:
    - role: layer2_infrastructure
      tags: [ 'layer2', 'infrastructure' ]
      mode: destroy
    - role: layer2_rhel
      tags: [ 'layer2','infrastructure', 'rhel' ]
      mode: destroy
    - role: layer2_vms
      tags: [ 'layer2','infrastructure', 'vms' ]
      mode: destroy



- hosts: test-rhel
  gather_facts: false
  remote_user: root
  roles:
    - role: layer2_vms
      tags: [ 'layer2',  "test-rhel", 'rhel' ]
      mode: start
    - role: layer2_rhel
      tags: [ 'layer2', 'rhel', 'test-rhel'  ]
      mode: destroy
    - role: layer2_vms
      tags: [ 'layer2', 'vms', 'test-rhel' ]
      mode: destroy

- hosts: rhevm
  remote_user: root
  gather_facts: false
  roles:
    - role: layer2_rhevm_ldap
      tags: [ 'rhevm-ldap' ]
      mode: destroy

- hosts: satellite
  gather_facts: false
  remote_user: root
  roles:
    - role: layer2_vms
      tags: [ 'layer2','satellite', 'rhel' ]
      mode: start
    - role: layer2_vms
      tags: [ 'layer2','satellite', 'rhel' ]
      mode: start
    - role: layer2_rhel
      tags: [ 'layer2','satellite', 'rhel'  ]
      mode: destroy
    - role: layer2_vms
      tags: [ 'layer2','satellite', 'vms' ]
      mode: destroy

- hosts: layer1
  gather_facts: false
  remote_user: root
  roles:
    # - role: layer1_vms
    #   tags: [ 'rhev', 'layer2', 'vm' ]
    #   mode: destroy
    #   group: rhev
    - role: layer1_rhev
      tags: [ 'rhev' ]
      mode: destroy
    # - role: layer1_vms
    #   tags: [ 'satellite', 'layer2', 'vm' ]
    #   mode: destroy
    #   group: satellite
    # - role: layer1_vms
    #   tags: [ 'rhosp', 'layer2', 'vm' ]
    #   mode: destroy
    #   group: rhosp-all
    - role: layer1_rhosp
      tags: [ 'rhosp' ]
      mode: destroy
      group: rhosp-all
    - role: layer1
      tags: [ 'layer1' ]
      mode: destroy
